### ISSUE TITLE
[UX] Dashboard: Update table widget

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-application#1155]
Acceptance Criteria

- [ ] The user should be able to scroll horizontally
- [ ] The user should be able to scroll vertically
- [ ] The user should be able to change the column width

PS: all the above is applicable in both edit and view mode
```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/iot-application/issues/1156
- [ ] https://github.com/awslabs/iot-application/issues/1157
- [ ] https://github.com/awslabs/iot-application/issues/1158
- [ ] https://github.com/awslabs/iot-application/issues/1159
```

**Comment by mnischay** [comment]
closing this, we already have an issue create here - https://github.com/awslabs/iot-app-kit/issues/1858
