### ISSUE TITLE
Home page - parent task

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-application#1274]
Parent task for issues involving the home page

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/iot-application/issues/1279
- [ ] https://github.com/awslabs/iot-application/issues/1281
- [ ] https://github.com/awslabs/iot-application/issues/1282
- [ ] https://github.com/awslabs/iot-application/issues/1283
- [ ] https://github.com/awslabs/iot-application/issues/1284
- [ ] https://github.com/awslabs/iot-application/issues/1285
- [ ] https://github.com/awslabs/iot-application/issues/1286
- [ ] https://github.com/awslabs/iot-application/issues/1334
- [ ] https://github.com/awslabs/iot-application/issues/1346
```
