### ISSUE TITLE
Dashboard create: update copy on dashboard creation workflow

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-application#1276]
Series of minor copy and validation on the dashboard create workflow

(Picture of sections current state which - NOT the intended end state)
<img width="879" alt="Screenshot 2023-09-20 at 11 28 50 AM" src="https://github.com/awslabs/iot-application/assets/77755322/6edff139-0dc5-4d5d-8db2-6ccadf7bd152">

```[tasklist]
### Tasks
- [ ] Remove "General Details"  header text
- [ ] Move "Create a dashboard to monitor your assets and properties." text to be under the "Create dashboard" header text
- [ ] Change "Create dashboard" button to just say "Create"
- [ ] In the create form, change "Dashboard name" to just "Name" 
- [ ] In the create form, change "Dashboard description" to just "description", and mark as required

```

**Comment by diehbria** [comment]
addressed in https://github.com/awslabs/iot-application/pull/1321
