### ISSUE TITLE
Home page: Remove all buttons from "Getting started" section

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-application#1283]
Remove all buttons from "whats new section"

(current state with buttons)
<img width="1469" alt="Screenshot 2023-09-20 at 11 44 10 AM" src="https://github.com/awslabs/iot-application/assets/77755322/35e9c5a4-4bf7-455c-99d6-5aa43b086d0a">

```[tasklist]
### Tasks
- [ ] Remove "explore widgets" button
- [ ] Remove "learn about assets" button
- [ ] Remove "whats new" button
- [ ] Remove "create dashboard" button
```

**Comment by diehbria** [comment]
addressed in https://github.com/awslabs/iot-application/pull/1320
