### ISSUE TITLE
 deadlink next to "getting started"

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-application#1754]
## Description

Various info links on centurion point to no where, this task is to either update them or remove them entirely such that every single info link points to useful information.

```[tasklist]
### Tasks
- [ ] Update info link next to "getting started" to point to the user guide
- [ ] Remove all info links from dashboard create (none point anywhere)
- [ ] go through the rest of centurion and remove any info link that points to no where
```

**Comment by YadhunandanGowda** [comment]
Hi,
right now the info link which is next to "getting started" is pointing to "https://github.com/awslabs/iot-application/blob/main/docs/user-guide.md", could you please confirm that this is the right one or not, if not please provide me the correct endpoint.

**Comment by diehbria** [comment]
When you click the link - it goes to a 404 so it is not the correct link. search the repo you will find a user guide that will have the correct path

**Comment by YadhunandanGowda** [comment]
@diehbria  Thank you, got the file and I replace the link.
