### ISSUE TITLE
[UX] Homepage for Centurion

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-application#945]
### Acceptance criteria

- [x] Display "getting started" container using expandable container component with action stripe from cloudscape library
- [x] "Getting started" container should remain expanded (default state)
- [x] Use key value pair component within the "getting started" container to display information
- [x] Use accurate spacing/padding information as provided in the cloudscape
- [x] Use accurate font + font styling 

### Overview

* **Current state:** No homepage. User needs to open the hamburger menu to access the list of dashboards or even to create a dashboard.
* **Proposed solution:** Refer to the image below -
    * Overview section to provide a high-level information about Centurion with the ability to hide. 
    * Dashboard table for creating, viewing and deleting the dashboard.
    * Users can further edit their dashboard once they view it.

<img width="1421" alt="Screenshot 2023-08-08 at 8 32 12 PM" src="https://github.com/awslabs/iot-application/assets/141063047/63e82fc1-bd66-411a-bb64-5fd3b8d307c7">

### NOTES

1. use https://refresh.cloudscape.aws.dev/
2. external link https://cloudscape.design/
3. use the visual refresh version as shown in the parent ticket screenshot / figma
4. use the design tokens where ever necessary for spacing and colors
5. https://cloudscape.design/components/app-layout/?tabId=api --> understand how app-layout works

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/iot-application/issues/949
- [ ] https://github.com/awslabs/iot-application/issues/994
- [ ] https://github.com/awslabs/iot-application/issues/1056
- [ ] https://github.com/awslabs/iot-application/issues/1057
- [ ] https://github.com/awslabs/iot-application/issues/1100
- [ ] https://github.com/awslabs/iot-application/issues/1101
```

**Comment by boweihan** [comment]
![Screenshot 2023-08-08 at 11 06 57 AM](https://github.com/awslabs/iot-application/assets/10264198/155ff2f6-9cb6-483b-b1e1-68423e3a4608)

**Comment by nadeswal** [comment]
Note:
Please make sure you use correct font styling. Refer to [LINK](https://refresh.cloudscape.aws.dev/foundation/visual-foundation/typography/)


Reference links:

Cloudscape app layout - [LINK](https://refresh.cloudscape.aws.dev/components/app-layout/?tabId=api)
Cloudscape expandable container - [LINK](https://refresh.cloudscape.aws.dev/components/expandable-section/?tabId=playground&example=container-with-interactive-header-elements&props=N4IgJgpgZghgrgGwC4FEAeAHGA7SYQBcSATnBADQgBuMxAljkoSAMYD22SMd2ExIlFgAs6CMMQjZmAZQgQABAE82cYvJZwAzkjYBbdRyh0A5qphI6HeUL4QAdAJA2YkYgEEWFjpuYAeAEJwSDrYAHwoYHRIvgD0gcEcoY7OrgCS2FBsfgAyPADW8jT0jAC8ADogPJkVoemZsbnYeUmUKXwAKhBoTAQgbmCRXtgwCAYZJmZDIAC%2BQA)
Cloudscape table - [LINK](https://refresh.cloudscape.aws.dev/components/table/?tabId=playground)

Padding preview for the landing page:

![padding](https://github.com/awslabs/iot-application/assets/141063047/d9f95b5a-d935-44e5-864a-35ebbb8d3fd1)

SVGs for the illustrations used in the design:

![visual_1](https://github.com/awslabs/iot-application/assets/141063047/10f07ba5-fbf5-48d4-a907-35ce14d597b7)

![visual_2](https://github.com/awslabs/iot-application/assets/141063047/932b784c-aade-4b5c-a7f3-e8b03d98816c)

![visual_3](https://github.com/awslabs/iot-application/assets/141063047/59f6d6ac-4bf0-4987-bf08-7aa2c2edd18f)

++ Don't hesitate to reach out for any questions.

**Comment by nadeswal** [comment]
Updated illustrations

<img width="1771" alt="Screenshot 2023-08-23 at 1 07 39 PM" src="https://github.com/awslabs/iot-application/assets/141063047/66160815-bd70-4da3-9a44-90d8360a42cd">
![visual 1](https://github.com/awslabs/iot-application/assets/141063047/3e6bad6c-6ac9-4d4d-afbb-5be3a417ce4e)
![visual 2](https://github.com/awslabs/iot-application/assets/141063047/ac3acd3b-e8ea-48a3-9e24-7f137fb64255)
![visual 3](https://github.com/awslabs/iot-application/assets/141063047/d3cdec3a-f4f3-48e3-9be3-fa99c7ad105a)
