### ISSUE TITLE
Create dashboard Page

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-application#946]
Rework needed for the creation flow. It should match the cloudscape pattern.

User Action: Click "Create dashboard" → Fills the form → Dashboard created. The user goes back to the "List of dashboards" view page.  

Newly created dashboard is pre-selected and the user clicks on "View" to edit the dashboard in the "Edit" mode.

Refer -
Doc - https://quip-amazon.com/5U2EAtnId09B/Centurion-UX-Pre-GA
Design - https://www.figma.com/file/pmsbdMcD7ieVWRFMNxStIi/VoT--AppKit-%26-Centurion?type=design&node-id=348%3A423854&mode=design&t=1zPNBiyI9sH6mezN-1
```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/iot-application/issues/1110
- [ ] https://github.com/awslabs/iot-application/issues/1111
- [ ] https://github.com/awslabs/iot-application/issues/1112
```

**Comment by diehbria** [comment]
tasks completed but PRs not associated back to issues
